version: "3"
services:

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/config/nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - ./docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./application/:/var/www/application/
    ports:
      - "80:80"
    networks:
      - internal

  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/config/php/Dockerfile
    volumes:
      - ./application/:/var/www/application/
      - ./docker/config/php/php.ini-development:/usr/local/etc/php/php.ini
    networks:
      - internal

networks:
  internal:
    driver: bridge