version: "3"
services:

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/config/nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - ./docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx/:/var/log/nginx/
      - ./application/:/var/www/application/
    ports:
      - "80:80"
    networks:
      - internal

  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/config/php/Dockerfile
    volumes:
      - ./docker/config/php/init.sh:/var/www/init.sh
      - ./docker/config/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./docker/config/php/www.conf:/usr/local/etc/php/www.conf
      - ./docker/log/php/:/var/log/
      - ./application/:/var/www/application/:cache
      - /var/www/application/var/cache
      #- /var/www/application/vendor
    tty: true
    networks:
      - internal

networks:
  internal:
    driver: bridge
